[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cert_program = "FtQmRp2snFfe2vx51ErzEfQzoTsSFpo3Ev2z1jer4Ezr"

[workspace]
members = ["programs/cert-program"]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --ignore '**/node_modules/**'"

[test]
startup_wait = 60000
